version: '3.8'

services:
  my-sql-write-read-replica:
    image: mysql:8.0
    container_name: my-sql-write-read-replica
    environment:
      MYSQL_ROOT_PASSWORD: Root1234!
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: replica_user
      MYSQL_PASSWORD: Replica1234!
    volumes:
      - ./mysql-certs:/etc/mysql/certs
    ports:
      - "3306:3306"
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=ecommerce_db
      --require_secure_transport=ON
      --ssl-ca=/etc/mysql/certs/ca-cert.pem
      --ssl-cert=/etc/mysql/certs/server-cert.pem
      --ssl-key=/etc/mysql/certs/server-key.pem
    networks:
      - mysql-net
    restart: always

  mysql-read-replica-1:
    image: mysql:8.0
    container_name: mysql-read-replica-1
    environment:
      MYSQL_ROOT_PASSWORD: Root1234!
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: replica_user
      MYSQL_PASSWORD: Replica1234!
    volumes:
      - ./mysql-certs:/etc/mysql/certs
    ports:
      - "3307:3306"
    command: >
      --server-id=2
      --log-bin=mysql-bin      
      --relay-log=slave-relay-bin
      --read-only=ON
      --require_secure_transport=ON
      --ssl-ca=/etc/mysql/certs/ca-cert.pem
      --ssl-cert=/etc/mysql/certs/client-cert.pem
      --ssl-key=/etc/mysql/certs/client-key.pem
    networks:
      - mysql-net
    restart: always

  mysql-read-replica-2:
    image: mysql:8.0
    container_name: mysql-read-replica-2
    environment:
      MYSQL_ROOT_PASSWORD: Root1234!
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: replica_user
      MYSQL_PASSWORD: Replica1234!
    volumes:
      - ./mysql-certs:/etc/mysql/certs
    ports:
      - "3308:3306"
    command: >
      --server-id=3
      --log-bin=mysql-bin
      --relay-log=slave-relay-bin
      --read-only=ON
      --require_secure_transport=ON
      --ssl-ca=/etc/mysql/certs/ca-cert.pem           
      --ssl-cert=/etc/mysql/certs/client-cert.pem     
      --ssl-key=/etc/mysql/certs/client-key.pem       
    networks:
      - mysql-net
    restart: always

  mysql-read-replica-3:
    image: mysql:8.0
    container_name: mysql-read-replica-3
    environment:
      MYSQL_ROOT_PASSWORD: Root1234!
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: replica_user
      MYSQL_PASSWORD: Replica1234!
    volumes:
      - ./mysql-certs:/etc/mysql/certs
    ports:
      - "3309:3306"
    command: >
      --server-id=4
      --log-bin=mysql-bin
      --relay-log=slave-relay-bin
      --read-only=ON
      --require_secure_transport=ON
      --ssl-ca=/etc/mysql/certs/ca-cert.pem
      --ssl-cert=/etc/mysql/certs/client-cert.pem
      --ssl-key=/etc/mysql/certs/client-key.pem
    networks:
      - mysql-net
    restart: always

networks:
  mysql-net:
    driver: bridge
